# ============================================
# Notification Service Yapılandırması
# ============================================

server:
  port: 8085

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
  
  # RabbitMQ Yapılandırması
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 2

springdoc:
  info:
    title: Notification Service API
    description: Notification Management Microservice - Bildirim yönetimi API dokümantasyonu
    version: 1.0.0

