filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/microservices/*.log
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      service: microservices
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_docker_metadata: ~

